server:
  port: 8080

napcat:
  adapter:
    type: websocket-client
    websocket-client:
      url: ws://127.0.0.1:3001
      token: "token"

  bot:
    self-id: 机器人qq号
    command-prefix: ""
    ignore-self-message: true

  llm:
    provider: openai
    openai:
      base-url: http://api.ai.com/v1
      api-key: ${OPENAI_API_KEY:apikey}
      model: qwem3.5-4b

  agent:
    enabled: true
    max-react-rounds: 5
    system-prompt: "你是一个有用的 QQ 机器人助手。"
    show-tool-process: true          # 将工具调用过程发送到群聊
    max-history-messages: 40         # 会话历史截断上限

logging:
  level:
    com.napcat: DEBUG
