server:
  port: 8080

napcat:
  adapter:
    type: websocket-client
    websocket-client:
      url: ws://154.201.84.30:3001
      token: "wzh20041001"

  bot:
    self-id: 1994463852
    command-prefix: ""
    ignore-self-message: true

  llm:
    provider: openai
    openai:
      base-url: http://154.201.84.30:12345/v1
      api-key: ${OPENAI_API_KEY:sk-wzh20041001}
      model: qwem3.5-4b

  agent:
    enabled: true
    max-react-rounds: 5
    system-prompt: "你是一个有用的 QQ 机器人助手。"

logging:
  level:
    com.napcat: DEBUG
